wandb_version: 1

layer_1:
  desc: null
  value: 100
activation_1:
  desc: null
  value: tanh
optimizer:
  desc: null
  value: adam
loss:
  desc: null
  value: sparse_categorical_crossentropy
metric:
  desc: null
  value: accuracy
epoch:
  desc: null
  value: 100
batch_size:
  desc: null
  value: 128
_wandb:
  desc: null
  value:
    python_version: 3.7.16
    cli_version: 0.15.8
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1691530587.472241
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.7.16
      5: 0.15.8
      8:
      - 3
      - 5
